-- File: ram.vhd
-- Generated by MyHDL 0.11
-- Date: Sat Nov 14 17:49:19 2020


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity ram is
    port (
        clk_i: in std_logic;
        wr_i: in std_logic;
        addr_i: in unsigned(8 downto 0);
        data_i: in unsigned(23 downto 0);
        data_o: out unsigned(23 downto 0)
    );
end entity ram;
-- Inputs:
--   clk_i:  Data is read/written on the rising edge of this clock input.
--   wr_i:   When high, data is written to the RAM; when low, data is read from the RAM.
--   addr_i: Address bus for selecting which RAM location is being read/written.
--   data_i: Data bus for writing data into the RAM.
-- Outputs:
--   data_o: Data bus for reading data from the RAM.

architecture MyHDL of ram is



type t_array_mem is array(0 to 512-1) of unsigned(23 downto 0);
signal mem: t_array_mem;

begin




RAM_LOC_INSTS_CHUNK_INSTS_K: process (clk_i) is
begin
    if rising_edge(clk_i) then
        if bool(wr_i) then
            mem(to_integer(addr_i)) <= data_i;
        else
            data_o <= mem(to_integer(addr_i));
        end if;
    end if;
end process RAM_LOC_INSTS_CHUNK_INSTS_K;

end architecture MyHDL;
